const products = [
  {
    id: '98173u9e1892',
    price: 347,
    name: 'Nike Sacai Blazer Amarelo e Vermelho',
    category: 'Dia a dia',
    brand: 'Nike',
    color: ['Amarelo', 'Vermelho'],
    description: [
      'O tênis Sacai Blazer, da marca Nike, é a escolha perfeita para quem busca conforto e estilo no dia a dia. Com um design moderno e versátil, ele pode ser usado para qualquer ocasião, seja para ir trabalhar, para passear ou para praticar atividades físicas leves.',
      'O tênis é feito com materiais de alta qualidade, que garantem durabilidade e conforto. A parte superior é confeccionada em couro sintético, que é macio e respirável. A sola é de borracha, que proporciona estabilidade e aderência.',
      'Aqui estão algumas características específicas do tênis:',
      'Design moderno e versátil',
      'Confortável para o dia a dia',
      'Feito com materiais de alta qualidade',
      'Durável e resistente',
      'Disponível em diversas cores e tamanhos',
      'O tênis Nike Sacai Blazer é a escolha perfeita para quem busca um tênis que seja bonito, confortável e durável. Ele é um investimento que vale a pena.',
    ],
    avaliation: 4,
    imageUrl:
      'https://images.pexels.com/photos/2529157/pexels-photo-2529157.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1',
  },
  {
    id: 'r0jf032j03r',
    price: 512,
    name: 'Nike Air Jodan J1 Laranja',
    category: 'Dia a dia',
    brand: 'Nike',
    color: ['Laranja', 'Branco'],
    description: [
      'O tênis Air Jodan J1, da marca Nike, é a escolha perfeita para quem busca conforto e estilo no dia a dia. Com um design moderno e versátil, ele pode ser usado para qualquer ocasião, seja para ir trabalhar, para passear ou para praticar atividades físicas leves.',
      'O tênis é feito com materiais de alta qualidade, que garantem durabilidade e conforto. A parte superior é confeccionada em couro sintético, que é macio e respirável. A sola é de borracha, que proporciona estabilidade e aderência.',
      'Aqui estão algumas características específicas do tênis:',
      'Design moderno e versátil',
      'Confortável para o dia a dia',
      'Feito com materiais de alta qualidade',
      'Durável e resistente',
      'Disponível em diversas cores e tamanhos',
      'O tênis Nike Air Jodan J1 é a escolha perfeita para quem busca um tênis que seja bonito, confortável e durável. Ele é um investimento que vale a pena.',
    ],
    avaliation: 5,
    imageUrl:
      'https://images.pexels.com/photos/9252069/pexels-photo-9252069.png?auto=compress&cs=tinysrgb&w=600&lazy=load',
  },
  {
    id: '982yr98hfr3',
    price: 250,
    name: 'Nike Air Jodan J1 Branco e Preto',
    category: 'Dia a dia',
    brand: 'Nike',
    color: ['White', 'Preto'],
    description: [
      'O tênis Air Jodan J1, da marca Nike, é a escolha perfeita para quem busca conforto e estilo no dia a dia. Com um design moderno e versátil, ele pode ser usado para qualquer ocasião, seja para ir trabalhar, para passear ou para praticar atividades físicas leves.',
      'O tênis é feito com materiais de alta qualidade, que garantem durabilidade e conforto. A parte superior é confeccionada em couro sintético, que é macio e respirável. A sola é de borracha, que proporciona estabilidade e aderência.',
      'Aqui estão algumas características específicas do tênis:',
      'Design moderno e versátil',
      'Confortável para o dia a dia',
      'Feito com materiais de alta qualidade',
      'Durável e resistente',
      'Disponível em diversas cores e tamanhos',
      'O tênis Nike Air Jodan J1 é a escolha perfeita para quem busca um tênis que seja bonito, confortável e durável. Ele é um investimento que vale a pena.',
    ],
    avaliation: 3,
    imageUrl:
      'https://images.pexels.com/photos/11281577/pexels-photo-11281577.jpeg?auto=compress&cs=tinysrgb&w=600&lazy=load',
  },
  {
    id: '23uhr54hth93r',
    price: 678,
    name: 'Nike Air Jodan J1 Rosa e Azul',
    category: 'Dia a dia',
    brand: 'Nike',
    color: ['Rosa', 'Azul'],
    description: [
      'O tênis Air Jodan J1, da marca Nike, é a escolha perfeita para quem busca conforto e estilo no dia a dia. Com um design moderno e versátil, ele pode ser usado para qualquer ocasião, seja para ir trabalhar, para passear ou para praticar atividades físicas leves.',
      'O tênis é feito com materiais de alta qualidade, que garantem durabilidade e conforto. A parte superior é confeccionada em couro sintético, que é macio e respirável. A sola é de borracha, que proporciona estabilidade e aderência.',
      'Aqui estão algumas características específicas do tênis:',
      'Design moderno e versátil',
      'Confortável para o dia a dia',
      'Feito com materiais de alta qualidade',
      'Durável e resistente',
      'Disponível em diversas cores e tamanhos',
      'O tênis Nike Air Jodan J1 é a escolha perfeita para quem busca um tênis que seja bonito, confortável e durável. Ele é um investimento que vale a pena.',
    ],
    avaliation: 4,
    imageUrl:
      'https://images.pexels.com/photos/10373341/pexels-photo-10373341.jpeg?auto=compress&cs=tinysrgb&w=600&lazy=load',
  },
  {
    id: '1-ur-1urj-u3',
    price: 365,
    name: 'Nike Air Jodan J1 Amarelo e Branco',
    category: 'Dia a dia',
    brand: 'Nike',
    color: ['Amarelo', 'Preto'],
    description: [
      'O tênis Air Jodan J1, da marca Nike, é a escolha perfeita para quem busca conforto e estilo no dia a dia. Com um design moderno e versátil, ele pode ser usado para qualquer ocasião, seja para ir trabalhar, para passear ou para praticar atividades físicas leves.',
      'O tênis é feito com materiais de alta qualidade, que garantem durabilidade e conforto. A parte superior é confeccionada em couro sintético, que é macio e respirável. A sola é de borracha, que proporciona estabilidade e aderência.',
      'Aqui estão algumas características específicas do tênis:',
      'Design moderno e versátil',
      'Confortável para o dia a dia',
      'Feito com materiais de alta qualidade',
      'Durável e resistente',
      'Disponível em diversas cores e tamanhos',
      'O tênis Nike Air Jodan J1 é a escolha perfeita para quem busca um tênis que seja bonito, confortável e durável. Ele é um investimento que vale a pena.',
    ],
    avaliation: 5,
    imageUrl:
      'https://images.pexels.com/photos/13411905/pexels-photo-13411905.jpeg?auto=compress&cs=tinysrgb&w=600&lazy=load',
  },
  {
    id: 'dhf98f3h9h9h30',
    price: 150,
    name: 'Nike Air Jodan J1 Vermelho e Preto',
    category: 'Dia a dia',
    brand: 'Nike',
    color: ['Vermelho', 'Preto'],
    description: [
      'O tênis Air Jodan J1, da marca Nike, é a escolha perfeita para quem busca conforto e estilo no dia a dia. Com um design moderno e versátil, ele pode ser usado para qualquer ocasião, seja para ir trabalhar, para passear ou para praticar atividades físicas leves.',
      'O tênis é feito com materiais de alta qualidade, que garantem durabilidade e conforto. A parte superior é confeccionada em couro sintético, que é macio e respirável. A sola é de borracha, que proporciona estabilidade e aderência.',
      'Aqui estão algumas características específicas do tênis:',
      'Design moderno e versátil',
      'Confortável para o dia a dia',
      'Feito com materiais de alta qualidade',
      'Durável e resistente',
      'Disponível em diversas cores e tamanhos',
      'O tênis Nike Air Jodan J1 é a escolha perfeita para quem busca um tênis que seja bonito, confortável e durável. Ele é um investimento que vale a pena.',
    ],
    avaliation: 5,
    imageUrl:
      'https://images.pexels.com/photos/11209837/pexels-photo-11209837.jpeg?auto=compress&cs=tinysrgb&w=600&lazy=load',
  },
  {
    id: 'epfij093u4rpjo',
    price: 465,
    name: 'Nike Air Jodan J1 Azul e Branco',
    category: 'Dia a dia',
    brand: 'Nike',
    color: ['Azul', 'Branco'],
    description: [
      'O tênis Air Jodan J1, da marca Nike, é a escolha perfeita para quem busca conforto e estilo no dia a dia. Com um design moderno e versátil, ele pode ser usado para qualquer ocasião, seja para ir trabalhar, para passear ou para praticar atividades físicas leves.',
      'O tênis é feito com materiais de alta qualidade, que garantem durabilidade e conforto. A parte superior é confeccionada em couro sintético, que é macio e respirável. A sola é de borracha, que proporciona estabilidade e aderência.',
      'Aqui estão algumas características específicas do tênis:',
      'Design moderno e versátil',
      'Confortável para o dia a dia',
      'Feito com materiais de alta qualidade',
      'Durável e resistente',
      'Disponível em diversas cores e tamanhos',
      'O tênis Nike Air Jodan J1 é a escolha perfeita para quem busca um tênis que seja bonito, confortável e durável. Ele é um investimento que vale a pena.',
    ],
    avaliation: 4,
    imageUrl:
      'https://images.pexels.com/photos/1031955/pexels-photo-1031955.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1',
  },
  {
    id: 'ifj23hh-032j',
    price: 550,
    name: 'All Star Chuck Taylor',
    category: 'Dia a dia',
    brand: 'Adidas',
    color: ['Branco', 'Preto'],
    description: [
      'O tênis Adidas SuperStars, da marca Adidas, é a escolha perfeita para quem busca conforto e estilo no dia a dia. Com um design moderno e versátil, ele pode ser usado para qualquer ocasião, seja para ir trabalhar, para passear ou para praticar atividades físicas leves.',
      'O tênis é feito com materiais de alta qualidade, que garantem durabilidade e conforto. A parte superior é confeccionada em couro sintético, que é macio e respirável. A sola é de borracha, que proporciona estabilidade e aderência.',
      'Aqui estão algumas características específicas do tênis:',
      'Design moderno e versátil',
      'Confortável para o dia a dia',
      'Feito com materiais de alta qualidade',
      'Durável e resistente',
      'Disponível em diversas cores e tamanhos',
      'O tênis Adidas SuperStars é a escolha perfeita para quem busca um tênis que seja bonito, confortável e durável. Ele é um investimento que vale a pena.',
    ],
    avaliation: 5,
    imageUrl:
      'https://images.pexels.com/photos/1161528/pexels-photo-1161528.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1',
  },
  {
    id: 'fo3f9h1093hr',
    price: 270,
    name: 'All Star Chuck Taylor Bege',
    category: 'Dia a dia',
    brand: 'All Star',
    color: 'Bege',
    description: [
      'O tênis All Star Chuck Taylor, da marca All Star, é a escolha perfeita para quem busca conforto e estilo no dia a dia. Com um design moderno e versátil, ele pode ser usado para qualquer ocasião, seja para ir trabalhar, para passear ou para praticar atividades físicas leves.',
      'O tênis é feito com materiais de alta qualidade, que garantem durabilidade e conforto. A parte superior é confeccionada em couro sintético, que é macio e respirável. A sola é de borracha, que proporciona estabilidade e aderência.',
      'Aqui estão algumas características específicas do tênis:',
      'Design moderno e versátil',
      'Confortável para o dia a dia',
      'Feito com materiais de alta qualidade',
      'Durável e resistente',
      'Disponível em diversas cores e tamanhos',
      'O tênis All Star Chuck Taylor é a escolha perfeita para quem busca um tênis que seja bonito, confortável e durável. Ele é um investimento que vale a pena.',
    ],
    avaliation: 3,
    imageUrl:
      'https://images.pexels.com/photos/2969318/pexels-photo-2969318.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1',
  },
  {
    id: '3fuh39fh03h0',
    price: 389,
    name: 'All Star Chuck Taylor Preto',
    category: 'Dia a dia',
    brand: 'All Star',
    color: 'Preto',
    description: [
      'O tênis All Star Chuck Taylor, da marca All Star, é a escolha perfeita para quem busca conforto e estilo no dia a dia. Com um design moderno e versátil, ele pode ser usado para qualquer ocasião, seja para ir trabalhar, para passear ou para praticar atividades físicas leves.',
      'O tênis é feito com materiais de alta qualidade, que garantem durabilidade e conforto. A parte superior é confeccionada em couro sintético, que é macio e respirável. A sola é de borracha, que proporciona estabilidade e aderência.',
      'Aqui estão algumas características específicas do tênis:',
      'Design moderno e versátil',
      'Confortável para o dia a dia',
      'Feito com materiais de alta qualidade',
      'Durável e resistente',
      'Disponível em diversas cores e tamanhos',
      'O tênis All Star Chuck Taylor é a escolha perfeita para quem busca um tênis que seja bonito, confortável e durável. Ele é um investimento que vale a pena.',
    ],
    avaliation: 5,
    imageUrl:
      'https://images.pexels.com/photos/4846441/pexels-photo-4846441.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1',
  },
  {
    id: '31uhdh1hf023h',
    price: 256,
    name: 'All Star Chuck Taylor Branco',
    category: 'Dia a dia',
    brand: 'All Star',
    color: 'Branco',
    description: [
      'O tênis All Star Chuck Taylor, da marca All Star, é a escolha perfeita para quem busca conforto e estilo no dia a dia. Com um design moderno e versátil, ele pode ser usado para qualquer ocasião, seja para ir trabalhar, para passear ou para praticar atividades físicas leves.',
      'O tênis é feito com materiais de alta qualidade, que garantem durabilidade e conforto. A parte superior é confeccionada em couro sintético, que é macio e respirável. A sola é de borracha, que proporciona estabilidade e aderência.',
      'Aqui estão algumas características específicas do tênis:',
      'Design moderno e versátil',
      'Confortável para o dia a dia',
      'Feito com materiais de alta qualidade',
      'Durável e resistente',
      'Disponível em diversas cores e tamanhos',
      'O tênis All Star Chuck Taylor é a escolha perfeita para quem busca um tênis que seja bonito, confortável e durável. Ele é um investimento que vale a pena.',
    ],
    avaliation: 4,
    imageUrl:
      'https://images.pexels.com/photos/2946956/pexels-photo-2946956.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1',
  },
  {
    id: 'qhf09uj-3f-19',
    price: 237,
    name: 'Bota Preta',
    category: 'Dia a dia',
    brand: 'Bota',
    color: 'Preto',
    description: [
      'A bota de couro preto com salto baixo é a escolha perfeita para quem busca conforto e elegância. Com um design clássico e atemporal, ela pode ser usada em diversas ocasiões, desde o trabalho até o passeio.',
      'A bota é feita com couro de alta qualidade, que é durável e resistente. A parte superior é confeccionada em couro preto, que é elegante e sofisticado. O salto é baixo, proporcionando conforto e estabilidade.',
      'Aqui estão algumas características específicas da bota:',
      'Design clássico e atemporal',
      'Confortável para o dia a dia',
      'Feito com materiais de alta qualidade',
      'Durável e resistente',
      'Disponível em diversas cores e tamanhos',
      'A bota de couro preto com salto baixo é a escolha perfeita para quem busca uma bota que seja bonita, confortável e durável. Ela é um investimento que vale a pena.',
    ],
    avaliation: 5,
    imageUrl:
      'https://images.pexels.com/photos/2929281/pexels-photo-2929281.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1',
  },
];

export default products;
